// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// encode_block_fast
IntegerVector encode_block_fast(NumericMatrix mat);
RcppExport SEXP _HaploGeno_encode_block_fast(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(encode_block_fast(mat));
    return rcpp_result_gen;
END_RCPP
}
// ridge_solver_cpp
arma::vec ridge_solver_cpp(const arma::mat& X, const arma::vec& y, double lambda);
RcppExport SEXP _HaploGeno_ridge_solver_cpp(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(ridge_solver_cpp(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HaploGeno_encode_block_fast", (DL_FUNC) &_HaploGeno_encode_block_fast, 1},
    {"_HaploGeno_ridge_solver_cpp", (DL_FUNC) &_HaploGeno_ridge_solver_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_HaploGeno(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
