# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Encode Haplotypes (Optimized)
NULL

encode_block_fast <- function(mat) {
    .Call(`_HaploGeno_encode_block_fast`, mat)
}

ridge_solver_cpp <- function(X, y, lambda) {
    .Call(`_HaploGeno_ridge_solver_cpp`, X, y, lambda)
}

